### ISSUE TITLE
Extension not working in Opera since 4.0 update

### ISSUE THREAD

**Issue by m-leclercq** [animal-crossing-music-extension/ac-music-extension#80] opened 2020-02-14 07:33 UTC
As the title says, ever since the 4.0 update, the extension has stopped working on Opera despite the fact that it used worked fine before. 
I have tried different settings, reinstalling the extension, and toggling off the tracker blocker and ad blocker but nothing seems to help. I'm on Windows 10 and I'm not using a VPN.

**Comment by PikaDude** [comment] 2020-02-14 07:34
Duplicate of #62 and already fixed in develop.

**Closed as completed by PikaDude** 2020-02-14 07:34 UTC
Labels: bug, duplicate
