### ISSUE TITLE
Loop timers

### ISSUE THREAD

**Issue by JdotCarver** [animal-crossing-music-extension/ac-music-extension#18] opened 2016-02-15 12:43 UTC
Hey guys, I was updating loop timers when right off the bat I noticed some just freeze the extension. My syntax should be correct, are there any limitations or exceptions to the system? @kylechu 

https://github.com/JdotCarver/Animal-Crossing-Music-Extension/blob/Updating-loop-timers/scripts/LoopTimes.js

**Comment by kowsen** [comment] 2016-02-15 13:07
Which ones are freezing it? Those look like they should all work - I'll test them out when I wake up.

**Comment by JdotCarver** [comment] 2016-02-15 13:36
Simply the ones that are in commentary. As soon as I disable the commentary tags it freezes the extension and you can't play any of the music. That's why I found it weird, it affects way more than I thought it would so I don't really understand.

Ok, thanks Kyle. Good Night then!

**Comment by TheDirtySpaceman** [comment] 2016-02-15 17:22
You might want to check the documentation for set timeout. Some of the resolutions you have set look very tight. I wonder if perhaps it's an issue with how precise your time markers are.

Harold Houchin

**Comment by JdotCarver** [comment] 2016-02-16 07:56
Thing is they all are triple digit precision and the one that Kylechu already implemented work fine. And the first three work fine too whereas they all are equally precise.

**Comment by kowsen** [comment] 2016-02-16 08:37
You had a few numbers formatted incorrectly. Javascript doesn't recognize numbers with unnecessary leading zeros. For example, you can't type "00.32", you would need to use either "0.32" or ".32". Additionally, you can't structure the end time as "1.29.519" on line 44. The number represents seconds, not a timecode - you would want "89.519".

Also, "24" isn't a valid hour - the times are zero indexed and go from 0-23. You likely either mean for that to be 0, or all of your hour values are shifted one value too high.

Once I fixed these issues, everything worked perfect for me.

**Comment by kowsen** [comment] 2016-02-16 08:41
The reason why it was killing everything is because AudioManager is making the assumption that a "loopTimes" object exists when it attempts to play a song. Since the invalid numbers were causing a parsing error when creating that object, loopTimes === undefined and AudioManager crashes when it attempts to check the attributes of the nonexistent object.

I could change it so AudioManager will play regardless and only looping will break, but personally, I feel like it's better as it is now than to have it silently fail if someone messes up a loop time.

EDIT: Also, there is no maximum precision on the loop times. SetTimeout isn't guaranteed to give you more than ~2-3ms of precision, so there isn't much point going past three decimal places, but writing more precise times won't crash anything.

**Comment by kowsen** [comment] 2016-02-16 09:01
I made a pull request with the fixes I mentioned - #19 

Also, in the future if you have issues like this, I highly recommend using the web inspector for the background page. It makes it easy to track down the causes of simple bugs - that's how I tracked down what was causing this error. You can get to it through a link in the Manage Extensions page.

**Comment by JdotCarver** [comment] 2016-02-16 13:03
Thank you so much. <3
Though you didn't need to do a pull request I could've corrected it myself Haha, and these were only the first few, I am still doing the rest.

**Comment by kowsen** [comment] 2016-02-16 22:51
I had already gone through and corrected them so I could test whether that was the problem - doing the pull request only took about five seconds and I figured I might as well save you the trouble of redoing the work.

So this bug can be closed?

**Comment by PikaDude** [comment] 2020-01-19 11:40
This issue can be closed as the fix was merged.

**Closed as completed by PikaDude** 2020-01-19 11:40 UTC
Labels: bug, question
