### ISSUE TITLE
(feature request) Play random looping ambiance from NH

### ISSUE THREAD

**Issue by KIRIAH** [animal-crossing-music-extension/ac-music-extension#135] opened 2020-05-14 21:05 UTC
It would be cool to enable ambient loops that layer under the music. Since ambiance is ambiance i would assume the best quality would be to pull ambient loops from NH. would like to choose what "type" of ambiance you want (rain, beach, normal)

**Comment by PikaDude** [comment] 2020-05-17 12:11
Duplicate of #61

**Closed as completed by PikaDude** 2020-05-17 12:11 UTC
