### ISSUE TITLE
Live weather location.

### ISSUE THREAD

**Issue by javuwuu** [animal-crossing-music-extension/ac-music-extension#128] opened 2020-04-06 18:35 UTC
Well i´m trying to set my location for this option, but it says **"City not found"** 
I'm from Chile and i'm using the post code and the ISO code: 8780000 and CL and idk, srry for my bad english.

**Comment by PikaDude** [comment] 2020-04-07 01:20
Duplicate of #79

**Closed as completed by PikaDude** 2020-04-07 01:20 UTC
Labels: bug, duplicate
